version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.28
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
